services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:4000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=${DB_HOST}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "
      until pg_isready -h \$DB_HOST -U \$POSTGRES_USER; do
        echo 'Waiting for Postgres to be ready...';
        sleep 2;
      done;
      lsof -t -i:4000 | xargs -r kill -9;
      npm run db:migrate;
      npm run seed:concerts;
      npm run dev;
      "

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
